version: "3.5"
services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: ./docker/dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./docker/dockerfile
    ports:
      - 8080:80
    depends_on:
      - api
